config.set("colors.webpage.darkmode.enabled", True)

# taken from the output of stylix
config.load_autoconfig(False)
config.set("colors.completion.category.bg", "@base00")
config.set("colors.completion.category.border.bottom", "@base00")
config.set("colors.completion.category.border.top", "@base00")
config.set("colors.completion.category.fg", "@base0B")
config.set("colors.completion.even.bg", "@base00")
config.set("colors.completion.fg", "#bbc2cf")
config.set("colors.completion.item.selected.bg", "@base03")
config.set("colors.completion.item.selected.border.bottom", "@base03")
config.set("colors.completion.item.selected.border.top", "@base03")
config.set("colors.completion.item.selected.fg", "#bbc2cf")
config.set("colors.completion.item.selected.match.fg", "@base0B")
config.set("colors.completion.match.fg", "@base0B")
config.set("colors.completion.odd.bg", "@base01")
config.set("colors.completion.scrollbar.bg", "@base00")
config.set("colors.completion.scrollbar.fg", "#bbc2cf")
config.set("colors.contextmenu.disabled.bg", "@base01")
config.set("colors.contextmenu.disabled.fg", "@base00")
config.set("colors.contextmenu.menu.bg", "@base00")
config.set("colors.contextmenu.menu.fg", "#bbc2cf")
config.set("colors.contextmenu.selected.bg", "@base03")
config.set("colors.contextmenu.selected.fg", "#bbc2cf")
config.set("colors.downloads.bar.bg", "@base00")
config.set("colors.downloads.error.bg", "@base08")
config.set("colors.downloads.error.fg", "@base00")
config.set("colors.downloads.start.bg", "@base0B")
config.set("colors.downloads.start.fg", "@base00")
config.set("colors.downloads.stop.bg", "@base0C")
config.set("colors.downloads.stop.fg", "@base00")
config.set("colors.hints.bg", "@base01")
config.set("colors.hints.fg", "#bbc2cf")
config.set("colors.hints.match.fg", "@base0B")
config.set("colors.keyhint.bg", "@base00")
config.set("colors.keyhint.fg", "#bbc2cf")
config.set("colors.keyhint.suffix.fg", "#bbc2cf")
config.set("colors.messages.error.bg", "@base08")
config.set("colors.messages.error.border", "@base08")
config.set("colors.messages.error.fg", "@base00")
config.set("colors.messages.info.bg", "@base0B")
config.set("colors.messages.info.border", "@base0B")
config.set("colors.messages.info.fg", "@base00")
config.set("colors.messages.warning.bg", "@base0E")
config.set("colors.messages.warning.border", "@base0E")
config.set("colors.messages.warning.fg", "@base00")
config.set("colors.prompts.bg", "@base00")
config.set("colors.prompts.border", "1px solid @base00")
config.set("colors.prompts.fg", "#bbc2cf")
config.set("colors.prompts.selected.bg", "@base01")
config.set("colors.prompts.selected.fg", "#bbc2cf")
config.set("colors.statusbar.caret.bg", "@base03")
config.set("colors.statusbar.caret.fg", "#bbc2cf")
config.set("colors.statusbar.caret.selection.bg", "@base03")
config.set("colors.statusbar.caret.selection.fg", "#bbc2cf")
config.set("colors.statusbar.command.bg", "@base00")
config.set("colors.statusbar.command.fg", "#bbc2cf")
config.set("colors.statusbar.command.private.bg", "@base01")
config.set("colors.statusbar.command.private.fg", "#bbc2cf")
config.set("colors.statusbar.insert.bg", "@base0B")
config.set("colors.statusbar.insert.fg", "@base00")
config.set("colors.statusbar.normal.bg", "@base00")
config.set("colors.statusbar.normal.fg", "#bbc2cf")
config.set("colors.statusbar.passthrough.bg", "@base0C")
config.set("colors.statusbar.passthrough.fg", "@base00")
config.set("colors.statusbar.private.bg", "@base01")
config.set("colors.statusbar.private.fg", "#bbc2cf")
config.set("colors.statusbar.progress.bg", "@base0B")
config.set("colors.statusbar.url.error.fg", "@base08")
config.set("colors.statusbar.url.fg", "#bbc2cf")
config.set("colors.statusbar.url.hover.fg", "#bbc2cf")
config.set("colors.statusbar.url.success.http.fg", "@base0C")
config.set("colors.statusbar.url.success.https.fg", "@base0B")
config.set("colors.statusbar.url.warn.fg", "@base0E")
config.set("colors.tabs.bar.bg", "@base00")
config.set("colors.tabs.even.bg", "@base01")
config.set("colors.tabs.even.fg", "#bbc2cf")
config.set("colors.tabs.indicator.error", "@base08")
config.set("colors.tabs.indicator.start", "@base0C")
config.set("colors.tabs.indicator.stop", "@base0B")
config.set("colors.tabs.odd.bg", "@base00")
config.set("colors.tabs.odd.fg", "#bbc2cf")
config.set("colors.tabs.pinned.even.bg", "@base0B")
config.set("colors.tabs.pinned.even.fg", "@base00")
config.set("colors.tabs.pinned.odd.bg", "@base0C")
config.set("colors.tabs.pinned.odd.fg", "@base00")
config.set("colors.tabs.pinned.selected.even.bg", "@base03")
config.set("colors.tabs.pinned.selected.even.fg", "#bbc2cf")
config.set("colors.tabs.pinned.selected.odd.bg", "@base03")
config.set("colors.tabs.pinned.selected.odd.fg", "#bbc2cf")
config.set("colors.tabs.selected.even.bg", "@base03")
config.set("colors.tabs.selected.even.fg", "#bbc2cf")
config.set("colors.tabs.selected.odd.bg", "@base03")
config.set("colors.tabs.selected.odd.fg", "#bbc2cf")
config.set("colors.tooltip.bg", "@base00")
config.set("colors.tooltip.fg", "#bbc2cf")
config.set("colors.webpage.preferred_color_scheme", "dark")
config.set("fonts.default_family", "Iosevka Nerd Font Propo")
config.set("fonts.default_size", "12pt")
config.set("fonts.web.family.cursive", "Iosevka Nerd Font Propo")
config.set("fonts.web.family.fantasy", "Iosevka Nerd Font Propo")
config.set("fonts.web.family.fixed", "Iosevka Nerd Font Mono")
config.set("fonts.web.family.sans_serif", "Iosevka Nerd Font Propo")
config.set("fonts.web.family.serif", "Iosevka Nerd Font Propo")
config.set("fonts.web.family.standard", "Iosevka Nerd Font Propo")
config.set("fonts.web.size.default", 16)
config.set("hints.border", "1px solid @base00")
