format = """
[](#e78284)\
$python\
$username\
[](bg:#a6d189 fg:#e78284)\
$directory\
[](fg:#a6d189 bg:#8caaee)\
$git_branch\
$git_status\
[](fg:#8caaee bg:#ca9ee6)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#ca9ee6 bg:#babbf1)\
$time\
[ ](fg:#babbf1)\
$line_break\
$character
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#e78284 fg:#292c3c"
style_root = "bg:#e78284"
format = '[$user ]($style)'

[directory]
style = "bg:#a6d189 fg:#292c3c"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "../"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#ca9ee6 fg:#292c3c"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#ca9ee6 fg:#292c3c"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#ca9ee6 fg:#292c3c"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#8caaee fg:#292c3c"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#8caaee fg:#292c3c"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#ca9ee6 fg:#292c3c"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#ca9ee6 fg:#292c3c"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#ca9ee6 fg:#292c3c"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#ca9ee6 fg:#292c3c"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#ca9ee6 fg:#292c3c"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#ca9ee6 fg:#292c3c"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#3B4252"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#ca9ee6 fg:#292c3c"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#babbf1 fg:#292c3c"
format = '[ $time ]($style)'

[character]
format = '$symbol'
success_symbol = ' 󱞩 (fg:#00ff00)'
error_symbol = ' 󱞩 (fg:#ff0000)'
