#!/usr/bin/env bash
if [ $(hyprctl getoption general:layout | awk '/str/ {print $2}') = "\"dwindle\"" ]
then
	hyprctl keyword general:layout "master"
else
	hyprctl keyword general:layout "dwindle"
fi
