theme = "onedarker-transparent"

[editor]
line-number = "relative"
color-modes = true
auto-format = false

[editor.statusline]
left = ["mode", "read-only-indicator", "file-modification-indicator", "total-line-numbers"]
center = ["spinner", "file-base-name", "version-control"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
