;; This file is automatically generated by tangling packages in emacs'
;; config.org file

(define-module (config home services emacs)
  #:use-module (config packages emacs-xyz)
  #:use-module (gnu packages emacs)
  #:use-module (gnu packages cmake)
  #:use-module (gnu packages tree-sitter)
  #:use-module (gnu packages emacs-xyz)
  #:use-module (gnu packages mail)
  #:use-module (gnu home services)
  #:export (my/home-emacs-service))

(define my/home-emacs-service
  (simple-service 'emacs-packages
                  home-profile-service-type
                  (list emacs-next-pgtk
                        emacs-elcord
                        emacs-expand-region
                        emacs-direnv
                        emacs-stylix-theme
                        emacs-vertico
                        emacs-prescient
                        emacs-marginalia
                        emacs-orderless
                        emacs-corfu
                        emacs-indent-bars
                        emacs-ligature
                        emacs-rainbow-delimiters
                        emacs-nerd-icons-dired
                        emacs-beacon
                        emacs-rainbow-mode
                        emacs-eglot-java
                        tree-sitter-java
                        tree-sitter-c
                        tree-sitter-cpp
                        tree-sitter-rust
                        emacs-magit
                        emacs-haskell-mode
                        emacs-stumpwm-mode
                        emacs-cmake-mode
                        emacs-geiser-guile
                        emacs-paredit
                        emacs-vterm
                        emacs-vterm-toggle
                        emacs-guix
                        mu
                        isync
                        emacs-emms
                        emacs-toc-org
                        emacs-org-auto-tangle
                        emacs-visual-fill-column
                        emacs-org-bullets)))
