#!/usr/bin/env bash
while [ 2 -eq 2 ]
do
	mpc idle 1>/dev/null
	if [ "${1}" == "info" ]; then
		output="$(mpc | sed -n '1p')"
		if ! [ "$(echo """$output""" | cut -d ' ' -f1)" == "volume:" ]; then
			echo "🎵 ${output}" | cut -c -50 | sed 's/$/\.\.\./'
		else
			echo ""
		fi
	elif [ "${1}" == "paused" ]; then
		check="$(mpc | awk 'NR==2 {print $1}')"
		if [ "${check}" = "[playing]" ]; then
			echo " "
		elif [ "${check}" = "[paused]" ]; then
			echo "▶ "
		else
			echo ""
		fi
	fi
done
